#Still depends on triggering default gh deploy actions 
name: Zola Build
description: Build (and/or deploy) a getzola/zola site
author: Kenzi Connor
branding:
  icon: cast
  color: purple
inputs:
  root:
    description: Directory to use as root of project. Deploy does not like this and requires an addition checkout in root
    required: false
    default: '.'
    type: string
  config:
    description: Path to a config file other than config.toml in the root of project
    required: false
    default: 'config.toml'
    type: string
  base-url:
    description: Force the base URL to be that value (defaults to the one in config)
    required: false
    default: ''
    type: string
  drafts:
    description: Include drafts when loading the site
    required: false
    default: false
    type: boolean
  output-dir:
    description: Outputs the generated site in the given path (by default 'public' dir in project root)
    required: false
    default: 'public'
    type: string
  force:
    description: Force building the site even if output directory is non-empty
    required: false
    default: false
    type: boolean
  deploy:
    description: Push to GitHub-Pages using JamesIves/github-pages-deploy-action defaults
    required: false
    default: true
    type: boolean
  check:
    description: Check external links with `zola check`
    required: false
    default: true
    type: boolean
runs:
  using: composite
  steps:
    - name: output variables
      shell: bash
      run: echo '${{toJSON(inputs)}}'
    - uses: knzai/zola-cli@install
    - name: zola check
      if: inputs.check
      uses: knzai/zola-cli@check
      with:
        root: ${{inputs.root}}
        config: ${{inputs.config}}
        drafts: ${{inputs.drafts}}
    - name: zola build
      uses: knzai/zola-cli@build
      with:
        root: ${{inputs.root}}
        config: ${{inputs.config}}
        base-url: ${{inputs.base-url}}
        drafts: ${{inputs.drafts}}
        output-dir: ${{inputs.output-dir}}
        force: ${{inputs.force}}
    - name: Deploy 🚀
      if: inputs.deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{inputs.output-dir}}
      
